name: PHPUnit Checks

on:
  # Trigger this workflow on pushes to trunk. Since this branch
  # is protected, this will only run post-merge.
  push:
    branches:
      - trunk
  # Trigger this workflow on PRs to trunk. We don't want to run
  # the check on merges into other branches, since that's an
  # unnecessary bit of overhead.
  pull_request:
    branches:
      - trunk
  # Trigger this workflow on release creation as well. Releases
  # are fairly rare, so this should be ok. Remove this in the
  # future if it proves unnecessary.
  release:
    types:
      - created

jobs:
  phpunit:
    name: Run test suite (${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Test with phpunit
        run: vendor/bin/phpunit --no-coverage --configuration phpunit.ci.xml
